<?php
/**
 * Plugin Name: OpenRouter Auto Publisher
 * Plugin URI: https://example.com/
 * Description: Generates articles with OpenRouter free models, fetches relevant Pixabay images, sets basic SEO metadata, and publishes posts automatically.
 * Version: 1.0.0
 * Author: AutoGenerated
 * License: GPL2
 * Text Domain: openrouter-auto-publisher
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

class ORAIPublisher {
    private $option_name = 'orai_publisher_options';

    public function __construct() {
        add_action('admin_menu', array($this, 'register_admin_menu'));
        add_action('admin_post_orai_generate_post', array($this, 'handle_generate_post'));
        add_action('wp_head', array($this, 'output_seo_meta'));
    }

    public function register_admin_menu() {
        add_menu_page('OpenRouter AI Publisher', 'OR AI Publisher', 'manage_options', 'orai-publisher', array($this, 'render_generate_page'));
        add_submenu_page('orai-publisher', 'API Settings', 'API Settings', 'manage_options', 'orai-publisher-settings', array($this, 'render_settings_page'));
    }

    public function get_options() {
        $defaults = array('openrouter_key' => '', 'pixabay_key' => '');
        $options = get_option($this->option_name, array());
        return wp_parse_args($options, $defaults);
    }

    public function render_settings_page() {
        if (!current_user_can('manage_options')) {
            return;
        }
        if (isset($_POST['orai_save_settings'])) {
            check_admin_referer('orai_save_settings');
            $options = $this->get_options();
            $options['openrouter_key'] = sanitize_text_field($_POST['openrouter_key']);
            $options['pixabay_key'] = sanitize_text_field($_POST['pixabay_key']);
            update_option($this->option_name, $options);
            echo '<div class="updated"><p>Settings saved.</p></div>';
        }
        $opts = $this->get_options();
        ?>
        <div class="wrap">
            <h1>OR AI Publisher Settings</h1>
            <form method="post">
                <?php wp_nonce_field('orai_save_settings'); ?>
                <table class="form-table">
                    <tr>
                        <th scope="row"><label for="openrouter_key">OpenRouter API Key</label></th>
                        <td><input type="text" name="openrouter_key" id="openrouter_key" value="<?php echo esc_attr($opts['openrouter_key']); ?>" class="regular-text" /></td>
                    </tr>
                    <tr>
                        <th scope="row"><label for="pixabay_key">Pixabay API Key</label></th>
                        <td><input type="text" name="pixabay_key" id="pixabay_key" value="<?php echo esc_attr($opts['pixabay_key']); ?>" class="regular-text" /></td>
                    </tr>
                </table>
                <?php submit_button('Save Settings', 'primary', 'orai_save_settings'); ?>
            </form>
        </div>
        <?php
    }

    public function render_generate_page() {
        if (!current_user_can('manage_options')) {
            return;
        }
        ?>
        <div class="wrap">
            <h1>Generate Post</h1>
            <form action="<?php echo admin_url('admin-post.php'); ?>" method="post">
                <input type="hidden" name="action" value="orai_generate_post" />
                <?php wp_nonce_field('orai_generate_post'); ?>
                <table class="form-table">
                    <tr>
                        <th scope="row"><label for="orai_topic">Topic</label></th>
                        <td><input type="text" name="orai_topic" id="orai_topic" class="regular-text" required /></td>
                    </tr>
                    <tr>
                        <th scope="row"><label for="orai_model">OpenRouter Model</label></th>
                        <td><input type="text" name="orai_model" id="orai_model" class="regular-text" value="openchat/openchat-3.5-0106" /></td>
                    </tr>
                </table>
                <?php submit_button('Generate and Publish'); ?>
            </form>
        </div>
        <?php
    }

    public function handle_generate_post() {
        if (!current_user_can('manage_options')) {
            wp_die('Unauthorized');
        }
        check_admin_referer('orai_generate_post');

        $topic = sanitize_text_field($_POST['orai_topic']);
        $model = sanitize_text_field($_POST['orai_model']);

        $opts = $this->get_options();
        $or_key = $opts['openrouter_key'];
        $px_key = $opts['pixabay_key'];

        if (empty($or_key) || empty($px_key)) {
            wp_die('API keys are not configured.');
        }

        // Generate article via OpenRouter
        $prompt = 'Write a detailed, SEO-friendly blog post about ' . $topic . '.';
        $response = wp_remote_post('https://openrouter.ai/api/v1/chat/completions', array(
            'headers' => array(
                'Content-Type' => 'application/json',
                'Authorization' => 'Bearer ' . $or_key,
            ),
            'body' => wp_json_encode(array(
                'model' => $model,
                'messages' => array(
                    array('role' => 'system', 'content' => 'You are a helpful content generator.'),
                    array('role' => 'user', 'content' => $prompt),
                ),
            )),
            'timeout' => 60,
        ));

        if (is_wp_error($response)) {
            wp_die('OpenRouter request failed.');
        }

        $body = json_decode(wp_remote_retrieve_body($response), true);
        $content = $body['choices'][0]['message']['content'] ?? '';

        if (empty($content)) {
            wp_die('Failed to generate content.');
        }

        // Fetch image from Pixabay
        $img_resp = wp_remote_get('https://pixabay.com/api/?key=' . $px_key . '&q=' . urlencode($topic) . '&image_type=photo&per_page=3&safesearch=true');
        $img_url = '';
        if (!is_wp_error($img_resp)) {
            $img_body = json_decode(wp_remote_retrieve_body($img_resp), true);
            if (!empty($img_body['hits'])) {
                $img_url = $img_body['hits'][0]['largeImageURL'];
            }
        }

        if (!empty($img_url)) {
            $content = '<p><img src="' . esc_url($img_url) . '" alt="' . esc_attr($topic) . '" /></p>' . "\n" . $content;
        }

        $post_id = wp_insert_post(array(
            'post_title' => wp_strip_all_tags($topic),
            'post_content' => $content,
            'post_status' => 'publish',
        ));

        if (is_wp_error($post_id)) {
            wp_die('Failed to create post.');
        }

        // Basic SEO meta
        $seo_title = $topic . ' - ' . get_bloginfo('name');
        $seo_desc = wp_trim_words($content, 30);
        update_post_meta($post_id, '_orai_seo_title', $seo_title);
        update_post_meta($post_id, '_orai_seo_desc', $seo_desc);

        wp_redirect(admin_url('post.php?action=edit&post=' . $post_id));
        exit;
    }

    public function output_seo_meta() {
        if (is_single()) {
            global $post;
            $title = get_post_meta($post->ID, '_orai_seo_title', true);
            $desc = get_post_meta($post->ID, '_orai_seo_desc', true);
            if ($title) {
                echo '<meta name="title" content="' . esc_attr($title) . '" />' . "\n";
            }
            if ($desc) {
                echo '<meta name="description" content="' . esc_attr($desc) . '" />' . "\n";
            }
        }
    }
}

new ORAIPublisher();

